### ISSUE TITLE
Suggestion: disable the automatic start of the plugin by setting `timeout = 0`

### ISSUE THREAD

**Issue by farzadmf** [NStefan002/donut.nvim#5]
Hi,

First of all, the plugin really looks cool, great job!

One thing: from what I understand, `timeout` is the "screensaver timeout". I want to disable the automatic screen saver and only do it with the `:Donut` command.

I thought setting `timeout = 0` would achieve this, however, when I do that, it will be running forever, and I can't stop it.

I think it would be nice to have this feature similar to "normal" screensavers that can be disabled

**Comment by NStefan002** [comment]
Hi!
> First of all, the plugin really looks cool, great job!

Thanks!

> One thing: from what I understand, timeout is the "screensaver timeout". I want to disable the automatic screen saver and only do it with the :Donut command.
I thought setting timeout = 0 would achieve this, however, when I do that, it will be running forever, and I can't stop it.
I think it would be nice to have this feature similar to "normal" screensavers that can be disabled

That's a reasonable suggestion. I added it in the latest release. If you experience any bugs related to this, feel free to open up a new issue.
