### ISSUE TITLE
Donut fails to display with vertical splits when using colorful-winsep.nvim plugin

### ISSUE THREAD

**Issue by pumkinisawesome** [NStefan002/donut.nvim#9]
### Problem

First of all, I love this plugin! The donut animation is very satisfying, and I love that I can have it as a screensaver.

However, I realised that, for some reason, it doesn't like displaying in vertical splits. When I have a single window or a horizontal split, the donut displays fine, but when I have any vertical splits, I get an error:

```
Error executing vim. schedule lua callback: ...nd/.local/share/nvim/lazy/donut.nvim/lua/donut/donut.lua:134: attempt to get length of a nil value
stack traceback:
... nd/.local/share/nvim/lazy/donut.nvim/lua/donut/donut.lua:134: in function 'display_frame'
... nd/. local/share/nvim/lazy/donut.nvim/lua/donut/donut.lua:158: in function "
vim/_editor. lua: in function ‹vim/_editor.lua: 0>
```

Here is a screenshot of the error:
![CleanShot 2024-09-21 at 18 28 50@2x](https://github.com/user-attachments/assets/58a89459-cb23-47b7-885f-e2329ed4f3cb)

I realised that this error only happens and the Donut only fails to display when a vertical split is the buffer currently selected, as seen in this gif:

![CleanShot 2024-09-21 at 18 36 56](https://github.com/user-attachments/assets/b3e9e23a-a812-4cda-8ecf-f2ef9bde70c6)

### Steps to reproduce

1. Install Donut plugin (duh)
2. Create a vertical split, and ensure that the vertical split is currently being edited
3. Either wait for the screensaver to enable automatically, or call `:Donut`

### Neovim version (`nvim -v`)

NVIM v0.10.1

### Terminal name/version

iTerm2 Build 3.5.4

# EDIT

I have realised what was causing the problem! This problem vanishes when I disable the [colourful window separation plugin](https://github.com/nvim-zh/colorful-winsep.nvim) that I use, so I have edited the Issue title to reflect this.

**Comment by NStefan002** [comment]
Hi! I'm glad you like this plugin. Thanks for reporting this and for figuring out where the problem came from.

Do you mind testing the [fix branch](https://github.com/NStefan002/donut.nvim/tree/fix)? I just pushed a possible fix to your problem.

**Comment by pumkinisawesome** [comment]
Wow, that was fast! Yeah, that solves the problem! Thank you so much!

![CleanShot 2024-09-21 at 19 32 42](https://github.com/user-attachments/assets/a9adcb96-986f-4748-ac9b-ba4b9e4ff7dc)

**Comment by NStefan002** [comment]
Thanks for your help!
